src/Entity/Jeux.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\JeuxRepository")
 */
class Jeux
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\TypeJeux", inversedBy="idType", cascade={"persist", "remove"})
     */
    private $Type_de_jeux;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $Date_creation;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Console", inversedBy="idConsole", cascade={"persist", "remove"})
     */
    private $Console;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Editeur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Developpeur;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $video;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getTypeDeJeux(): ?TypeJeux
    {
        return $this->Type_de_jeux;
    }

    public function setTypeDeJeux(?TypeJeux $Type_de_jeux): self
    {
        $this->Type_de_jeux = $Type_de_jeux;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->Date_creation;
    }

    public function setDateCreation(?\DateTimeInterface $Date_creation): self
    {
        $this->Date_creation = $Date_creation;

        return $this;
    }

    public function getConsole(): ?Console
    {
        return $this->Console;
    }

    public function setConsole(?Console $Console): self
    {
        $this->Console = $Console;

        return $this;
    }

    public function getEditeur(): ?string
    {
        return $this->Editeur;
    }

    public function setEditeur(?string $Editeur): self
    {
        $this->Editeur = $Editeur;

        return $this;
    }

    public function getDeveloppeur(): ?string
    {
        return $this->Developpeur;
    }

    public function setDeveloppeur(?string $Developpeur): self
    {
        $this->Developpeur = $Developpeur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage1(): ?string
    {
        return $this->image1;
    }

    public function setImage1(?string $image1): self
    {
        $this->image1 = $image1;

        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(?string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }

    public function getImage3(): ?string
    {
        return $this->image3;
    }

    public function setImage3(?string $image3): self
    {
        $this->image3 = $image3;

        return $this;
    }

    public function getImage4(): ?string
    {
        return $this->image4;
    }

    public function setImage4(?string $image4): self
    {
        $this->image4 = $image4;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }
}

src/Form/GestionJeuxType.php
<?php

namespace App\Form;

use App\Entity\Jeux;
use App\Entity\TypeJeux;
use App\Entity\Console;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;



class GestionJeuxType extends AbstractType 
{
   
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Type_de_jeux', EntityType::class,[
                'required' => true,
                'placeholder' => 'Choississez un Type de jeux..',
                'class' => TypeJeux::class,
                'choice_label' => 'Nom_du_type'])
            ->add('Console', EntityType::class,[
                'required' => true,
                'placeholder' => 'Choississez une Console..',
                'class' => Console::class,
                'choice_label' => 'Nom'])
            ->add('Date_creation',DateType::class,[
                'widget' =>'single_text',
                'html5' => false,
                'format' => 'yyyy-MM-dd',
                'attr' => ['class' => 'js-datepicker']
            ])
            ->add('Editeur')
            ->add('Developpeur')
            ->add('Description')
            ->add('image1',FileType::class,['label' => 'Image 1','required' => false,'data_class' => null])
            ->add('image2', FileType::class,['label' => 'Image 2','required' => false,'data_class' => null])
            ->add('image3', FileType::class,['label' => 'Image 3','required' => false,'data_class' => null])
            ->add('image4', FileType::class,['label' => 'Image 4','required' => false,'data_class' => null])
            ->add('video')
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Jeux::class,
        ]);
    }
}

src/Controller/GestionJeuxController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Entity\Jeux;
use App\Entity\TypeJeux;
use App\Entity\Console;
use App\Service\FileUploader;
use App\Form\GestionJeuxType;
use App\Repository\JeuxRepository;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use App\Knp\Bundle\PaginatorBundle;
use Knp\Bundle\PaginatorBundle\KnpPaginatorBundle;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class GestionJeuxController extends Controller
{

      /**
     * @Route("/gestion/DeleteJeux/{id}", name="delete_jeux")
     */
    public function DeleteJeux(Request $request,Jeux $jeux)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($jeux);
        $entityManager->flush();


        $this->addFlash('success', 'Le Type de Jeux '.$jeux->getNom().' à bien été supprimé');
        return $this->redirectToRoute('liste_type');


    }


    /**
     * @Route("/gestion/GestionJeux", name="ajout_jeux")
     * @Route("/gestion/GestionJeux/{id}", name="modif_jeux")
     */
    public function index(Request $request,Jeux $jeux = null)
    {
        if(!$jeux ){
            $jeux = new Jeux();
        }
        
        $form = $this->CreateForm(GestionJeuxType::class, $jeux);

        $form->handlerequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $Jeux = $form->getData();
          
            if($image1 = $request->request->get('fileimage1'))
                    $Jeux->setImage1($image1);

            if($image2 = $request->request->get('fileimage2'))
                $Jeux->setImage2($image2); 
                
            if($image3 = $request->request->get('fileimage3'))
                $Jeux->setImage3($image3);

            if($image4 = $request->request->get('fileimage4'))
            $Console->setImage4($image4);

            $EntityManager = $this->getDoctrine()->getManager();
            $EntityManager->persist($Jeux);
            $EntityManager->flush();
 
             $this->addFlash("success","Le jeux ".$Jeux->getNom()." à été créé");


        }

        return $this->render('gestion_jeux/index.html.twig', [
            'form' =>$form->createView(),
            'Modif' =>$jeux->getId() != null,
            'Image1' => $jeux->getImage1(),
            'Image2' => $jeux->getImage2(),
            'Image3' => $jeux->getImage3(),
            'Image4' => $jeux->getImage4()
            
        ]);
    }

    /**
     * @Route ("/gestion/listeJeux", name="liste_jeux")
     */
    public function listeJeux (Request $request)
    {

        $repo = $this->getDoctrine()->getRepository(Jeux::class);
        $findAll = $repo->findAll();
        $count = count($findAll);
        $paginator  = $this->get('knp_paginator');
        
        // Paginate the results of the query
        $jeux = $paginator->paginate(
            // Doctrine Query, not results
            $findAll,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            5
        );


        return $this->render("/gestion_jeux/listeJeux.html.twig",[
            'count' => $count,
            'jeux' => $jeux
        ]);
    }
}

templates/gestion_jeux/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des jeux{% endblock %}

{% block body %}
{% include 'header.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
  {% for message in app.flashes('success') %}
            <div class="alert alert-success">
              <i class="fa fa-check"></i>
                {{ message }}
            </div>
        {% endfor %}


      {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
              <i class="fa fa-remove"></i>
                {{ message }}
            </div>
        {% endfor %}    

      {{form_start(form)}}

      {{form_row(form.Nom)}}
      {{form_row(form.Type_de_jeux)}}  
      {{form_row(form.Console)}}
      {{form_row(form.Date_creation)}}
      {{form_row(form.Editeur)}}
      {{form_row(form.Developpeur)}}
      {{form_row(form.Description)}}
     {% if Modif and Image1 %}
        
     <div class="form-group">
        <label for="gestion_Image1">logo</label>
       
            <div class="custom-file" >
            {{Image_logo}}
             <div id="image1IMG">
            <input type='hidden' id='gestion_image1' name='file1' value="{{Image1}}">
            </div>
            <button type="button" id="btn-modifier_image1" class="btn btn-success">Modifier</button>   
              <br />  
              <br />     
        </div>
            <div class="form-group" id="image-presente-image1">
                 <img src="/images-back/Fabricant/{{Image1}}" title="logo" width="30%"/><br />
             </div>
    </div>
     {%do form.image1.setRendered(true)%}
    {% else %}
    <!--<div class="form-group">
        <label for="gestion_fabricant_Image">Logo</label>
            <div class="custom-file">
                <input type="file" id="gestion_fabricant_Image" name="gestion_fabricant[Image]" class="custom-file-input" />
                 <label for="gestion_fabricant_Image" class="custom-file-label"></label>
            </div>
    </div>-->
    {{form_row(form.image1)}}
  

    {% endif %}
     {% if Modif and Image2 %}
        
     <div class="form-group">
        <label for="gestion_Image2">logo</label>
       
            <div class="custom-file" >
            {{Image_logo}}
             <div id="image2IMG">
            <input type='hidden' id='gestion_image2' name='file2' value="{{Image1}}">
            </div>
            <button type="button" id="btn-modifier_image2" class="btn btn-success">Modifier</button>   
              <br />  
              <br />     
        </div>
            <div class="form-group" id="image-presente-image2">
                 <img src="/images-back/Fabricant/{{Image2}}" title="logo" width="30%"/><br />
             </div>
    </div>
     {%do form.image2.setRendered(true)%}
    {% else %}
    <!--<div class="form-group">
        <label for="gestion_fabricant_Image">Logo</label>
            <div class="custom-file">
                <input type="file" id="gestion_fabricant_Image" name="gestion_fabricant[Image]" class="custom-file-input" />
                 <label for="gestion_fabricant_Image" class="custom-file-label"></label>
            </div>
    </div>-->
    {{form_row(form.image2)}}
  

    {% endif %}
      {% if Modif and Image3 %}
        
     <div class="form-group">
        <label for="gestion_Image3">logo</label>
       
            <div class="custom-file" >
            {{Image_logo}}
             <div id="image3IMG">
            <input type='hidden' id='gestion_image3' name='file3' value="{{Image3}}">
            </div>
            <button type="button" id="btn-modifier_image3" class="btn btn-success">Modifier</button>   
              <br />  
              <br />     
        </div>
            <div class="form-group" id="image-presente-image3">
                 <img src="/images-back/Fabricant/{{Image3}}" title="logo" width="30%"/><br />
             </div>
    </div>
     {%do form.image3.setRendered(true)%}
    {% else %}
    <!--<div class="form-group">
        <label for="gestion_fabricant_Image">Logo</label>
            <div class="custom-file">
                <input type="file" id="gestion_fabricant_Image" name="gestion_fabricant[Image]" class="custom-file-input" />
                 <label for="gestion_fabricant_Image" class="custom-file-label"></label>
            </div>
    </div>-->
    {{form_row(form.image3)}}
  

    {% endif %}
       {% if Modif and Image4 %}
        
     <div class="form-group">
        <label for="gestion_Image4">logo</label>
       
            <div class="custom-file" >
            {{Image_logo}}
             <div id="image4IMG">
            <input type='hidden' id='gestion_image4' name='file4' value="{{Image4}}">
            </div>
            <button type="button" id="btn-modifier_image4" class="btn btn-success">Modifier</button>   
              <br />  
              <br />     
        </div>
            <div class="form-group" id="image-presente-image4">
                 <img src="/images-back/Fabricant/{{Image4}}" title="logo" width="30%"/><br />
             </div>
    </div>
     {%do form.image4.setRendered(true)%}
    {% else %}
    <!--<div class="form-group">
        <label for="gestion_fabricant_Image">Logo</label>
            <div class="custom-file">
                <input type="file" id="gestion_fabricant_Image" name="gestion_fabricant[Image]" class="custom-file-input" />
                 <label for="gestion_fabricant_Image" class="custom-file-label"></label>
            </div>
    </div>-->
    {{form_row(form.image4)}}
  

    {% endif %}
      {{form_row(form.video)}}


        {% if Modif %}
         <button type="submit" class="btn btn-primary">Modifier</button>
    {% else %}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {% endif %} 
      {{form_end(form)}}
</div>

<script type="text/javascript">
  jQuery(function ($) {
    $('.js-datepicker').datepicker({
            dateFormat: 'yy-mm-dd'
        });

     var Modif = function(idImage,path,img){
                  
                      var template = '<input type="file" id="'+idImage+'" name="" class="custom-file-input" /><label for="'+idImage+'" class="custom-file-label"></label>';
                      $("#IMG"+img).parent().html(template);
                  
                      $("#image-presente-"+img).remove();
                      $('#'+idImage).on('change',function(){
                          ajaxImage(idImage,path,img); 
                      });
                 
                   }

            var ajaxImage = function(idImage,path,img){
       
                      //get the file name
               var fd = new FormData();
               var file_data = $('#'+idImage).prop('files')[0];
               fd.append('file',file_data);
               var fileName= $('#'+idImage).val();
              
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html('toto');
                waitingDialog.show('Chargement de l\'image');
              
               $.ajax({
                type:"post",    
                url:path,
                data:fd,
                enctype: 'multipart/form-data',
                processData: false,
                contentType: false,
                dataType:"json",
                success:function(data){
                    if(data.status == "success")
                     setTimeout(function () {waitingDialog.hide();
                                            $('.alert-danger').remove();
                                             $("#"+idImage).parent().html(data.newfilename+" &nbsp;<div id='IMG"+img+"'><input type='hidden' id='"+idImage+"' name='file"+img+"' value='"+data.newfilename+"'></div>");
                                             $("#"+idImage).parent().append('<button type="button" id="btn-modifier_'+idImage+'" class="btn btn-success">Modifier</button><br /><br />  ')
                                             $("#"+idImage).parent().after('<div class="form-group" id="image-presente_'+img+'"> <img src="/images-back/Fabricant/'+data.newfilename+'" title="logo" width="30%"/></div><br />');
                                             $("#btn-modifier_"+idImage).click(function(){
                                                 Modif(idImage,path,img);
                                                }); 
                                            }, 3000);
                     else{
                          setTimeout(function () {waitingDialog.hide();
                          
                        $("#"+idImage).parent().after('<div class="alert alert-danger">'+data.newfilename+'</div>');
                        
                           }, 3000);
                          
                        }
                    }
                   
                 

                });
                

            }


           $("#btn-modifier_gestion_jeux_image1").click(function(){
               Modif('gestion_jeux_image1','{{path("upload_image")}}','image1');
           }); 

           $('#gestion_jeux_image1').on('change',function(){
              ajaxImage('gestion_jeux_image1','{{path("upload_image")}}','image1');
             
            }); 

               $("#btn-modifier_gestion_jeux_image2").click(function(){
               Modif('gestion_jeux_image2','{{path("upload_image")}}','image2');
           }); 

           $('#gestion_jeux_image2').on('change',function(){
              ajaxImage('gestion_jeux_image2','{{path("upload_image")}}','image2');
             
            }); 

               $("#btn-modifier_gestion_jeux_image3").click(function(){
               Modif('gestion_jeux_image3','{{path("upload_image")}}','image3');
           }); 

           $('#gestion_jeux_image3').on('change',function(){
              ajaxImage('gestion_jeux_image3','{{path("upload_image")}}','image3');
             
            }); 

            $("#btn-modifier_gestion_jeux_image4").click(function(){
               Modif('gestion_jeux_image4','{{path("upload_image")}}','image4');
           }); 

           $('#gestion_jeux_image4').on('change',function(){
              ajaxImage('gestion_jeux_image4','{{path("upload_image")}}','image4');
             
            }); 
      
        


  }); 
</script>        
{% endblock %}

templates/gestion_jeux/listeJeux.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% include 'header.html.twig' %}

<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>


<div class="example-wrapper">

<h1>Gestion des Jeux</h1>

   {% for message in app.flashes('success') %}
            <div class="alert alert-success">
              <i class="fa fa-check"></i>
                {{ message }}
            </div>
        {% endfor %}

   {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
              <i class="fa fa-remove"></i>
                {{ message }}
            </div>
        {% endfor %}      

  {% if count == 0 %}
      <div class="alert alert-info">
        Il n'y a aucun Jeux d'enregistré
      </div>
  {% else %}
      <div class="list-group">
        <a href="#" class="list-group-item active" title="Secteurs d'activité">
            Liste des Jeux
        </a>
  {% endif %}  
  
    {% for jeuxx in jeux %}
    <li class="list-group-item d-flex justify-content-between" title="Fabricant">
      <div class="align-items-start">
       {{jeuxx.nom}}&nbsp; 
       </div>
      <div class="align-items-start">
        <a href="{{path('modif_console',{'id' :jeuxx.id })}}" class="fa fa-edit"></a>
         <a href="#" class="fa fa-trash-o " data-toggle="modal" data-target="#exampleModal{{jeuxx.id}}"></a>
      </div>
    </li>
    {% endfor %}
  </div> 
 
   <div class="navigation text-center">
            {{ knp_pagination_render(jeux) }}
        </div>

  {% for item in jeux %}
     {% include 'modal_jeux.html.twig' %}
  {% endfor %}
</div>
{% endblock %}